#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__

#undef CONFIG_DEBUG
#define ENABLE_DEBUG 0
#define IF_DEBUG(...)
#define IF_NOT_DEBUG(...) __VA_ARGS__

#define CONFIG_FEATURE_SYSLOG 1
#define ENABLE_FEATURE_SYSLOG 1
#define IF_FEATURE_SYSLOG(...) __VA_ARGS__
#define IF_NOT_FEATURE_SYSLOG(...)

#undef CONFIG_FEATURE_EDITING_ASK_TERMINAL
#define ENABLE_FEATURE_EDITING_ASK_TERMINAL 0
#define IF_FEATURE_EDITING_ASK_TERMINAL(...)
#define IF_NOT_FEATURE_EDITING_ASK_TERMINAL(...) __VA_ARGS__

#undef CONFIG_FEATURE_LESS_ASK_TERMINAL
#define ENABLE_FEATURE_LESS_ASK_TERMINAL 0
#define IF_FEATURE_LESS_ASK_TERMINAL(...)
#define IF_NOT_FEATURE_LESS_ASK_TERMINAL(...) __VA_ARGS__

#define CONFIG_VI 1
#define ENABLE_VI 1
#define IF_VI(...) __VA_ARGS__
#define IF_NOT_VI(...)

#define CONFIG_FEATURE_VI_MAX_LEN 4096
#define ENABLE_FEATURE_VI_MAX_LEN 1
#define IF_FEATURE_VI_MAX_LEN(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_MAX_LEN(...)

#undef CONFIG_FEATURE_VI_8BIT
#define ENABLE_FEATURE_VI_8BIT 0
#define IF_FEATURE_VI_8BIT(...)
#define IF_NOT_FEATURE_VI_8BIT(...) __VA_ARGS__

#define CONFIG_FEATURE_VI_COLON 1
#define ENABLE_FEATURE_VI_COLON 1
#define IF_FEATURE_VI_COLON(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_COLON(...)

#define CONFIG_FEATURE_VI_YANKMARK 1
#define ENABLE_FEATURE_VI_YANKMARK 1
#define IF_FEATURE_VI_YANKMARK(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_YANKMARK(...)

#define CONFIG_FEATURE_VI_SEARCH 1
#define ENABLE_FEATURE_VI_SEARCH 1
#define IF_FEATURE_VI_SEARCH(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_SEARCH(...)

#undef CONFIG_FEATURE_VI_REGEX_SEARCH
#define ENABLE_FEATURE_VI_REGEX_SEARCH 0
#define IF_FEATURE_VI_REGEX_SEARCH(...)
#define IF_NOT_FEATURE_VI_REGEX_SEARCH(...) __VA_ARGS__

#define CONFIG_FEATURE_VI_USE_SIGNALS 1
#define ENABLE_FEATURE_VI_USE_SIGNALS 1
#define IF_FEATURE_VI_USE_SIGNALS(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_USE_SIGNALS(...)

#define CONFIG_FEATURE_VI_DOT_CMD 1
#define ENABLE_FEATURE_VI_DOT_CMD 1
#define IF_FEATURE_VI_DOT_CMD(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_DOT_CMD(...)

#define CONFIG_FEATURE_VI_READONLY 1
#define ENABLE_FEATURE_VI_READONLY 1
#define IF_FEATURE_VI_READONLY(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_READONLY(...)

#define CONFIG_FEATURE_VI_SETOPTS 1
#define ENABLE_FEATURE_VI_SETOPTS 1
#define IF_FEATURE_VI_SETOPTS(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_SETOPTS(...)

#define CONFIG_FEATURE_VI_SET 1
#define ENABLE_FEATURE_VI_SET 1
#define IF_FEATURE_VI_SET(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_SET(...)

#define CONFIG_FEATURE_VI_WIN_RESIZE 1
#define ENABLE_FEATURE_VI_WIN_RESIZE 1
#define IF_FEATURE_VI_WIN_RESIZE(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_WIN_RESIZE(...)

#define CONFIG_FEATURE_VI_ASK_TERMINAL 1
#define ENABLE_FEATURE_VI_ASK_TERMINAL 1
#define IF_FEATURE_VI_ASK_TERMINAL(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_ASK_TERMINAL(...)

#define CONFIG_FEATURE_VI_UNDO 1
#define ENABLE_FEATURE_VI_UNDO 1
#define IF_FEATURE_VI_UNDO(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_UNDO(...)

#define CONFIG_FEATURE_VI_UNDO_QUEUE 1
#define ENABLE_FEATURE_VI_UNDO_QUEUE 1
#define IF_FEATURE_VI_UNDO_QUEUE(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_UNDO_QUEUE(...)

#define CONFIG_FEATURE_VI_UNDO_QUEUE_MAX 256
#define ENABLE_FEATURE_VI_UNDO_QUEUE_MAX 1
#define IF_FEATURE_VI_UNDO_QUEUE_MAX(...) __VA_ARGS__
#define IF_NOT_FEATURE_VI_UNDO_QUEUE_MAX(...)

#endif
